version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  labels:
  - "type: maintenance"
  ignore:
  - dependency-name: setuptools
    versions:
    - 52.0.0
    - 53.0.0
    - 54.0.0
    - 54.1.1
    - 54.1.2
    - 54.1.3
    - 54.2.0
  - dependency-name: sphinx
    versions:
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: tox
    versions:
    - 3.21.2
    - 3.21.3
    - 3.21.4
    - 3.22.0
  - dependency-name: sphinx-rtd-theme
    versions:
    - 0.5.1
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: mypy
    versions:
    - "0.800"
